spring:
  application:
    name: product
  datasource:
     username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    jpa: show-sql:true
  rabbitmq:
      host: 192.168.21.38
      port: 5672
      username: admin
      password: dengyang    
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
