spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.21.38:3306/springcloud_sell?useUnicode=true&characterEncoding=utf-8
    jpa: show-sql:true
  redis:
    host: 192.168.21.38
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
